DEBUG 2020-12-07 14:57:31.446 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-07 14:57:31.446 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-07 14:57:31.446 UTC: 	 Executing command: 'status'
DEBUG 2020-12-07 14:57:31.447 UTC: 	 Found CRAB cache file /lustrehome/gmilella/.crab3
ERROR 2020-12-07 14:57:31.449 UTC: 	 Error: crab_projects/crab_gem_dpg_ntuple_mwgr5_run338714_express_last/ is not a valid CRAB project directory.
ERROR 2020-12-07 14:57:31.449 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_gem_dpg_ntuple_mwgr5_run338714_express_last/ is not a valid CRAB project directory.
INFO 2020-12-07 14:57:31.452 UTC: 	 Log file is /lustrehome/gmilella/NTuples3108/CMSSW_11_1_4/src/MuDPGAnalysis/MuonDPGNtuples/src/crab.log
